import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './navbar/page'
import Image from 'next/image'
import styles from './skills/skillcards.module.css'
import menu from './navbar/menu.svg'
//  

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chomydev Portfolio',
  description: 'Generated by create next app',
}
// const [menuList, setMenuList] = useState(false)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Navbar />
        </nav>
        {children}
      </body>
    </html>
  )
}
